/**
 * Created by artis on 20/07/2017.
 */

export const BUSINESS_VERIFY_SIGNUP_REQUEST = "BUSINESS_VERIFY_SIGNUP_REQUEST";
export const BUSINESS_VERIFY_SIGNUP_SUCCESS = "BUSINESS_VERIFY_SIGNUP_SUCCESS";
export const BUSINESS_VERIFY_SIGNUP_FAILURE = "BUSINESS_VERIFY_SIGNUP_FAILURE";
