/**
 * Created by artis on 20/07/2017.
 */

/* Signup verification / activate account  */
export const BUSINESS_VERIFY_SIGNUP_REQUEST = "BUSINESS_VERIFY_SIGNUP_REQUEST";
export const BUSINESS_VERIFY_SIGNUP_SUCCESS = "BUSINESS_VERIFY_SIGNUP_SUCCESS";
export const BUSINESS_VERIFY_SIGNUP_FAILURE = "BUSINESS_VERIFY_SIGNUP_FAILURE";

export const BUSINESS_SIGNUP_REQUEST = "BUSINESS_SIGNUP_REQUEST";
export const BUSINESS_SIGNUP_SUCCESS = "BUSINESS_SIGNUP_SUCCESS";
export const BUSINESS_SIGNUP_FAILURE = "BUSINESS_SIGNUP_FAILURE";

export const BUSINESS_SIGNUP_REMAINING_REQUEST = "BUSINESS_SIGNUP_REMAINING_REQUEST";
export const BUSINESS_SIGNUP_REMAINING_SUCCESS = "BUSINESS_SIGNUP_REMAINING_SUCCESS";
export const BUSINESS_SIGNUP_REMAINING_FAILURE = "BUSINESS_SIGNUP_REMAINING_FAILURE";