export const SET_TITLE = "SET_TITLE";

export const LOGIN_REQUEST = "LOGIN_REQUEST";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAILURE = "LOGIN_FAILURE";

export const LOGOUT = "LOGOUT";

export const GLOBAL_SNACKBAR_OPEN = "GLOBAL_SNACKBAR_OPEN";
export const GLOBAL_SNACKBAR_CLOSE = "GLOBAL_SNACKBAR_CLOSE";

export const SET_ROLES = "SET_ROLES";
export const CHANGE_ROLE = "CHANGE_ROLE";
export const SET_NAME = "SET_NAME";
export const SET_ACCOUNT_INFO = "SET_ACCOUNT_INFO";

export const SET_SECTIONS = "SET_SECTIONS";

export const SET_ALL_MEMBERS = "SET_ALL_MEMBERS";
export const SET_PAYMENTS_FOR_MEMBER = "SET_PAYMENTS_FOR_MEMBER";
export const SET_PAYMENTS = "SET_PAYMENTS";
export const OPEN_PAYMENT_DIALOG = "OPEN_PAYMENT_DIALOG";
export const CLOSE_PAYMENT_DIALOG = "CLOSE_PAYMENT_DIALOG";
export const PAID_UNTIL_DATE = "PAID_UNTIL_DATE";
export const SET_AMOUNT = "SET_AMOUNT";

export const SET_CLASSES = "SET_CLASSES";
export const SET_CLASS = "SET_CLASS";
export const QUERING_CLASSES = "QUERING_CLASSES";
export const SET_CLASS_MEMBER = "SET_CLASS_MEMBER";
export const SET_CLASSES_FOR_MEMBER = "SET_CLASSES_FOR_MEMBER";


export const CHOOSE_FOR_CHECKIN = "CHOOSE_FOR_CHECKIN";
export const CHEKIN_CHOSEN = "CHEKIN_CHOSEN";
export const SET_UNCHECKED_MEMBERS = "SET_UNCHECKED_MEMBERS";
export const CHEKIN_CONFIRM = "CHEKIN_CONFIRM";
export const CLOSE_CONFIRM = "CLOSE_CONFIRM";
export const MEMBERS_SENT = "MEMBERS_SENT";
export const SET_CLASS_TITLE = "SET_CLASS_TITLE";
export const QUERING_MEMBERS = "QUERING_MEMBERS";


export const SET_ERROR = "SET_ERROR";
export const SET_MESSAGE = "SET_MESSAGE";


