/**
 * Created by artis on 25/04/2017.
 */

//import { createConstants } from '../utils';

export const SET_TITLE = "SET_TITLE";

export const LOGIN_REQUEST = "LOGIN_REQUEST";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAILURE = "LOGIN_FAILURE";
// signup
export const SIGNUP_VERIFY_EMAIL_REQUEST = "SIGNUP_VERIFY_EMAIL_REQUEST";
export const SIGNUP_VERIFY_EMAIL_SUCCESS = "SIGNUP_VERIFY_EMAIL_SUCCESS";
export const SIGNUP_VERIFY_EMAIL_FAILURE = "SIGNUP_VERIFY_EMAIL_FAILURE";

export const LOGOUT = "LOGOUT";

export const GLOBAL_SNACKBAR_OPEN = "GLOBAL_SNACKBAR_OPEN";
export const GLOBAL_SNACKBAR_CLOSE = "GLOBAL_SNACKBAR_CLOSE";

export const SET_ROLES = "SET_ROLES";
export const CHANGE_ROLE = "CHANGE_ROLE";
export const SET_NAME = "SET_NAME";
export const SET_ACCOUNT_INFO = "SET_ACCOUNT_INFO";

export const SET_STATEMENT = "SET_STATEMENT";

export const SET_SECTIONS = "SET_SECTIONS";

export const CHOOSE_FOR_CHECKIN = "CHOOSE_FOR_CHECKIN";
export const CHEKIN_CHOSEN = "CHEKIN_CHOSEN";
export const SET_UNCHECKED_MEMBERS = "SET_UNCHECKED_MEMBERS";
export const CHEKIN_CONFIRM = "CHEKIN_CONFIRM";
export const CLOSE_CONFIRM = "CLOSE_CONFIRM";
export const MEMBERS_SENT = "MEMBERS_SENT";


